# Generated by Django 5.0.6 on 2024-07-03 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_rename_posts_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='lesson_plan',
            field=models.FileField(max_length=254, null=True, upload_to=''),
        ),
    ]
