# Generated by Django 5.0.6 on 2024-07-03 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_lesson_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='lesson_plan',
            field=models.FileField(max_length=254, null=True, upload_to='Uploaded_Files/'),
        ),
    ]
