# Generated by Django 5.0.6 on 2024-07-08 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_post_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='lesson_plan',
            field=models.FileField(null=True, upload_to='Uploaded_Files/'),
        ),
    ]
