# Generated by Django 5.0.6 on 2024-07-08 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_alter_post_lesson_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='lesson_plan',
            field=models.FileField(blank=True, null=True, upload_to='Uploaded_Files/'),
        ),
    ]
