# Generated by Django 5.0.6 on 2024-07-12 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_post_is_verified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='is_verified',
            new_name='verified',
        ),
    ]
