# Generated by Django 5.0.6 on 2024-07-31 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_rename_post_comment_lesson_comment_body_comment_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='lesson',
            new_name='post',
        ),
    ]
