name: Django CI Pipeline

on:
  pull_request:
    branches:
      - kwcortum-patch-1 
      - KennysBranch
jobs:
  test-django-app:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12"]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Set file Permissions Part 1
        run: mkdir -p /home/runner/work/Lesson_Plan_Database_Project/Teachers_Help_Teachers/Uploaded_Files
      - name: Set file Permissions Part 2
        run: chmod 777 /home/runner/work/Lesson_Plan_Database_Project/Teachers_Help_Teachers/Uploaded_Files
      - name: Install dependency pip
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Install dependency requests
        run: |
          python -m pip install requests
      - name: Install Django
        run: |
          python -m pip install Django
      - name: Run Django tests
        run: |
          cd Teachers_Help_Teachers
          python manage.py test
