name: Django CI

on:
  pull_request:
    branches: [main, kwcortum-patch-1, KennysBranch]
jobs:
  test-django-app:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12"]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Install Django
        run: |
          python -m pip install Django
      - name: Run Post Model Test
        run: |
          cd Teachers_Help_Teachers
          python manage.py test Teachers_Help_Teachers.PostModelTestCase
      - name: Run Add Function View Test
        run: |
          python manage.py test Teachers_Help_Teachers.AddFunctionViewTest
      - name: Run Download File View Test
        run: |
          python manage.py test Teachers_Help_Teachers.DownloadFileViewTest
      - name: Run Search Function View Test
        run: |
          python manage.py test Teachers_Help_Teachers.SearchFunctionViewTest
          
